apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qqiqxha9f-nodejs 
  janus-idp.io/tekton: qqiqxha9f-nodejs
  backstage.io/kubernetes-id: qqiqxha9f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qqiqxha9f-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml